### PR TITLE
Changed the images source

### PR DESCRIPTION
**Pull request by benda1997**

### CODE REVIEW

**Comment by sckott** [comment]
Thanks @benda1997 ! Looks good to me

**Comment by benda1997** [comment]
@sckott I am new to R. Can you please guide how to start contributing to projects.

**Comment by sckott** [comment]
@benda1997 i can try to help, do you have specific questions? do you want to know how to contribute on github, or do you have that sorted out?

**Comment by benda1997** [comment]
@sckott  I know how to contribute on GitHub. Can you suggest me a good project based on R , on which I can contribute on the codebase and also polish my ML skills.

**Comment by sckott** [comment]
i assume by ML you mean machine learning?  in ropensci we don't do any machine learning stuff, but you there is a summary here https://cran.rstudio.com/web/views/MachineLearning.html of the machine learning stuff in R you can contribute to. 

if you want to stick with ropensci, we have many isssues open with hacktoberfest label to which you can contribute if you like

**Pull request merged**
